{% set name = "mask" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jacobdeichert/mask/archive/v{{ version }}.tar.gz
  sha256: abe5fddc7ea1a1ffab59c8f0823a95c7a6fdcfe86749f816b06d7690319d56aa

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - mask --help

about:
  home: https://github.com/jacobdeichert/mask
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI task runner defined by a simple markdown file
  dev_url: https://github.com/jacobdeichert/mask

extra:
  recipe-maintainers:
    - danielnachun
