context:
  version: 0.11.6

package:
  name: mask
  version: ${{ version }}

source:
  url: https://github.com/jacobdeichert/mask/archive/refs/tags/mask/${{ version }}.tar.gz
  sha256: e76ae20a120c3ab44f1b14e73ff3f1b39d900bc66f8d2dab7fed4706bacd92fd

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - mask --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI task runner defined by a simple markdown file
  homepage: https://github.com/jacobdeichert/mask
  repository: https://github.com/jacobdeichert/mask

extra:
  recipe-maintainers:
    - danielnachun
